### ISSUE TITLE
Clarification on field enhancement plotting

### ISSUE THREAD

**Issue by VSales-fis** [Trel725/plasmon-meep#1]
Hello!
I'm trying to understand the following plot:
https://github.com/Trel725/plasmon-meep/blob/3b48f20dfb3e26301a637df408ca5ec482891bdf/visualize_freqs.py#L60

If you want to plot the field enhancement as you labeled it:
https://github.com/Trel725/plasmon-meep/blob/3b48f20dfb3e26301a637df408ca5ec482891bdf/visualize_freqs.py#L62

Shouldn't you plot the square root of the enhancement? Since the get_power function:
https://github.com/Trel725/plasmon-meep/blob/3b48f20dfb3e26301a637df408ca5ec482891bdf/caculate2d_field_disk_cache.py#L44

Returns:

https://github.com/Trel725/plasmon-meep/blob/3b48f20dfb3e26301a637df408ca5ec482891bdf/caculate2d_field_disk_cache.py#L56

Thanks in advance!

**Comment by Trel725** [comment]
Hello,

Thank you for that issue. Obviously you are right and there must be  $|\\vec{E}$/$\\vec{E_0}|^2$`, i.e. ratio of energies instead of the previous version. I have corrected the code. Feel free to ask other questions by reopening that issue or creating new one, I will try to answer them more quickly than this one.
