### ISSUE TITLE
Questions about source

### ISSUE THREAD

**Issue by yu-ting-py** [Trel725/plasmon-meep#3]
I have some questions:

1. Your script "perform_fdtd.py" uses a magnetic current as a point source. Why not use electric current?
2. How do choose "cfreq" and "fwidth" parameters in "perform_fdtd.py"? What do they change?

Thanks!

**Comment by Trel725** [comment]
Hello, 

1. Magnetic field in Z direction will cause electric fields lying in the XY plane. Quotation from the MEEP documentation:

> The consequence of this is that the fields can be chosen purely polarized: either Hz polarized (electric field in the plane and magnetic field in the z direction) or Ez polarized (magnetic field in the plane and electric field in the z direction).

2. These parameters define a frequency range for the simulation. E.g. if you want to cover the range 1-1.5 um, then you first need to calculate the corresponding meep frequencies (since meep uses its own frequency definition, see docs)  
```
f1 = 1/1 um = 1  
f2 = 1/1.5 um = 0.667 
```
With that freqs in mind:  
```
cfreq  = (f1+f2)/2 (central frequency of Gaussian pulse)
fwidth = (f1-f2) (width of Gaussian pulse)
```

That's it.

**Comment by yu-ting-py** [comment]
Hi

Thanks for your response.

If I want to change source into a plane wave propagating along x- or y-axis, what do I need to change?

**Comment by Trel725** [comment]
Please see the Meep documentation [here](https://meep.readthedocs.io/en/latest/Python_User_Interface/#source) or [here](https://meep.readthedocs.io/en/latest/FAQ/#usage-sources). However it makes little sense since you will be limited to a single frequency.
