### ISSUE TITLE
Citing the respository

### ISSUE THREAD

**Issue by VSales-fis** [Trel725/plasmon-meep#6]
Hello, Andrii! Firstly, thank you for your great scripts.

I'm looking to cite your repository in my master thesis, and I'm wondering how would you prefer me to do that (direct link, accompanying paper(s), etc).

Thanks in advance.

**Comment by Trel725** [comment]
Hi, Victor, thanks for interest in my scripts, hope they were useful for your thesis! There are, of course, no paper about that since the theory is old and widely known, the major work is done by Meep and mine scripts are just a bit of post-processing. So, you should definitely cite Meep according to [their docs](https://meep.readthedocs.io/en/latest/Acknowledgements). Then, if you'd like you can cite my repo as:
```
@misc{plasmon-meep-2019,
    author       = {Andrii Trelin},
    title        = {{plasmon-meep: a set of scripts for calculating plasmon resonance/electric field enhancement}},
    year         = 2019,
    howpublished = {\url{https://github.com/Trel725/plasmon-meep}},
    note = {Accessed: 22.03.2021}
    }
```
Also, you may want to replace the date format in the note to your local standard. If you do not use TEX, you can convert it to more familiar formats with [online tool](https://bibtex.online/).

Regards,
Andrii

**Comment by VSales-fis** [comment]
Got it! Once again, thank you very much!
